api/urls.py
from django.conf.urls import url

from api.views import check_version
from . import views

urlpatterns = [
    url(r'^users/$', views.UserViewSet.as_view()),
    url(r'^tasks/$', views.TaskViewSet.as_view()),
    url(r'^tasks/(?P<pk>[0-9]+)$', views.TaskDetailViewSet.as_view()),
    url(r'^tasks/(?P<pk>[0-9]+)/candidates/$', views.TaskDetailCandidate.as_view()),
    url(r'^candidate/$', views.TaskCandidateViewSet.as_view()),
    url(r'^candidate/(?P<pk>[0-9]+)$', views.CandidateProfile.as_view()),
    url(r'^check_version$', check_version, name='check_version')
]

b52/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from api.views import obtain_auth_token
from b52 import settings
from zoltan import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.log_in, name='login'),
    url(r'^logout/', views.log_out, name='logout'),
    url(r'^api/', include('api.urls')),
    url(r'^api-token-auth/', obtain_auth_token),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^profile/$', views.change_profile, name='change_profile'),
    url(r'^tasks/(?P<id>\d+)', views.detail_tasks, name='detail_tasks'),
    url(r'^tasks/', views.tasks, name='tasks'),
    url(r'^candidates/(?P<id>\d+)', views.candidates, name='candidates'),
    url(r'^candidates/', views.candidates, name='candidates'),
    url(r'^points/', views.points, name='points'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^channels-api/', include('channels_api.urls'))
]



# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zoltan/forms.py
from __future__ import unicode_literals

from django import forms
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import ugettext_lazy as _

UserModel = get_user_model()

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        User = get_user_model()
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2', )

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["email"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label=_("Email"), max_length=254)

    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        """
        Sends a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)

        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')

        email_message.send()

    def get_users(self, email):
        """Given an email, return matching user(s) who should receive a reset.

        This allows subclasses to more easily customize the default policies
        that prevent inactive users and users with unusable passwords from
        resetting their password.
        """
        active_users = UserModel._default_manager.filter(**{
            '%s__iexact' % UserModel.get_email_field_name(): email,
            'is_active': True,
        })
        return (u for u in active_users if u.has_usable_password())

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name=None,
             extra_email_context=None):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        email = self.cleaned_data["email"]
        for user in self.get_users(email):
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            context = {
                'email': email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
            }
            if extra_email_context is not None:
                context.update(extra_email_context)
            self.send_mail(
                subject_template_name, email_template_name, context, from_email,
                email, html_email_template_name=html_email_template_name,
            )


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(
        required=True,
        widget=forms.Textarea
    )


class profileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Yonchi</title>

    <!-- Bootstrap core CSS -->
    <link href={% static 'web/css/bootstrap.css' %} rel="stylesheet">

    <link href={% static 'web/css/navbar.css' %} rel="stylesheet">

    <link href={% static 'web/css/counter.css' %} rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div class="container">
    <!-- Static navbar -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">YOnchi</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href={% url 'dashboard' %}>Dashboard</a></li>
                    <li><a href={% url 'tasks' %}>Tasks</a></li>
                    <li><a href={% url 'candidates' %}>Candidates</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Signed in as <b>{{ request.user.get_full_name }}</b></li>
                    <li class="navbar-text" id="points"><img class="image-refresh" src="{% static "web/images/refresh_icon.png" %}" data-src="{% static 'web/images/refresh_icon1.png' %}"
                            data-hover="{% static 'web/images/refresh_icon1.png' %}"> <span id="point">{{ request.user.points }}</span></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My account <span id='badge' class="badge"></span> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href={% url 'change_profile' %}>Change profile</a></li>
                            <li><a href={% url 'change_password' %}>Change password</a></li>
                            <li><a href="#" data-toggle="modal" data-target="#notifications">Notifications <span id='badge1' class="badge"></span> </a></li>
                            <li class="divider"></li>
                            <li><a href={% url 'logout' %}>Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>

    <!-- Main component for a primary marketing message or call to action -->
    {% block main_block %}{% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src={% static 'web/js/bootstrap.min.js' %}></script>
    <script src={% static 'web/js/task_modal.js' %}></script>
    <script type="text/javascript" src="{% static 'web/js/footer.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/candidates.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/counter.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
        $(".nav li").on("click", function () {
            $(".nav li").removeClass("active");
            $(this).addClass("active");
        });
    </script>

    {#Change img when hover#}
    <script>
        $(".image-container").mouseover(function (e) {
            $(this).attr("src", $(this).attr("src").replace("setting.png", "setting1.png"));
        }).mouseout(function (e) {
            $(this).attr("src", $(this).attr("src").replace("setting1.png", "setting.png"));
        });
        $(".image-candidates").mouseover(function (e) {
            $(this).attr("src", $(this).attr("src").replace("candidates.png", "candidates1.png"));
        }).mouseout(function (e) {
            $(this).attr("src", $(this).attr("src").replace("candidates1.png", "candidates.png"));
        });
        $(".image-refresh").mouseover(function (e) {
            $(this).attr("src", $(this).attr("src").replace("refresh_icon.png", "refresh_icon1.png"));
        }).mouseout(function (e) {
            $(this).attr("src", $(this).attr("src").replace("refresh_icon1.png", "refresh_icon.png"));
        });
    </script>

    {#    JS SCRIPT FOR BOOTSRAT SELECT#}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>

    <!-- (Optional) Latest compiled and minified JavaScript translation files -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/i18n/defaults-*.min.js"></script>

    <script>
          google.charts.load('current', {
        'packages':['geochart'],
        // Note: you will need to get a mapsApiKey for your project.
        // See: https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings
        'mapsApiKey': 'AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY'
      });
      google.charts.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
{#          var a = [["Country", "Popularity"], ["Germany", 10]];#}
          var a = [["Country", "Popularity"], {{country|safe}}];
          var b = {{country|safe}};
        var data = google.visualization.arrayToDataTable(b);

        var options = {};

        var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));

        chart.draw(data, options);
      }
    </script>
    <script>
        var ws = new WebSocket('ws://127.0.0.1:8000/');
        var token_auth = "{{request.user.auth_token}}";
        var src_picture = "{% static 'web/images/read.png' %}";
        var data = {
            'stream': "notifications",
            'payload': {'action': "subscribe", 'data': {}, 'token': token_auth}
        };
        ws.onopen = function () {
            console.log("Opening a connection...");
            window.identified = false;
        };
        ws.onclose = function (evt) {
            console.log("I'm sorry. Bye!");
        };
        ws.onmessage = function (message) {
            var jsonObject = JSON.parse(message.data);
            var notification_counter = jsonObject.payload.data.length;
            var messages = jsonObject.payload.data;
            if (notification_counter >= 0) {
                document.getElementById("badge").innerHTML =notification_counter;
                document.getElementById("badge1").innerHTML =notification_counter;
                for (var i = 0, len = messages.length; i < len; i++) {
                    var id_message = messages[i]['id'];
                    var t = "{{ request.user.auth_token }}";
                    if($("[data-board-id="+id_message+"]").length === 0){
                        var mess = messages[i]['text'];
                        var date = messages[i]['created_at'];
                        $(excelDataTable).find('tbody').append( "<tr data-board-id="+ id_message +"><td>"+ mess +"</td><td>"+date+"</td><td><a id="+id_message+" class='readbtn' href='#' onclick=\"sendMyMessages('"+id_message+"','"+token_auth+"')\"><img src="+src_picture+"></a></td></tr>");
                    }
                }
            }
            console.log(jsonObject)
        };
        var msg = JSON.stringify(data);
        var wsSend = function(data) {
        if (!ws.readyState) {
            setTimeout(function () {
                wsSend(data);
            }, 100);
        } else {
            ws.send(data);
        }
        };
        wsSend(msg);

    </script>

{#    MODAL WINDOW TASK DETAIL#}
    <div class="modal fade" id="notifications" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4><span id="model_title"></span></h4>
                </div>
                <div id="form-modal-notif" class="modal-body">
{#                    <ol id="list">#}
{##}
{#                    </ol>#}
                    <table class="table table-hover" id="excelDataTable">
                        <thead>
                            <tr>
                                <th>Message</th>
                                <th>Created Date</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="tbody">
                            <tr data-board-id="" id="myrow">
                        </tbody>
                    </table>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

</div>
</body>
</html>

templates/change_password.html
{% extends "base.html" %}
{% load static %}

{% block main_block %}
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

                <div class="form-group">
                    <label for="id_old_password">Old Password</label>
                    <input type="password" class="form-control" name="old_password" autofocus required
                           id="id_old_password" placeholder="Old Password">
                    <div class="password-background"></div>
                </div>
                <div class="form-group">
                    <label for="id_new_password1">New Password</label>
                    <input type="password" class="form-control" name="new_password1" required id="id_new_password1"
                           placeholder="New Password">
                    <div class="password-background"></div>
                </div>
                <div class="form-group">
                    <label for="id_new_password2">Confirm Password</label>
                    <input type="password" class="form-control" name="new_password2" required id="id_new_password2"
                           placeholder="Confirm Password">
                    <div class="password-background"></div>
                </div>
                <button class="btn btn-success btn-lg btn-block" type="submit">Save changes</button>
            </div>
        </div>
    </form>



{% endblock %}

templates/login.html
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href={% static 'web/css/main.css' %}>
    <script>
    $(function() {
    $('#forgot-form').hide();
    $('#login-form-link').click(function(e) {
    	$("#login-form").delay(100).fadeIn(100);
 		$("#register-form").fadeOut(100);
 		$("#forgot-form").fadeOut(100);
		$('#register-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});
    $('.forgot-password').click(function(e) {
    	$("#forgot-form").delay(100).fadeIn(100);
 		$("#register-form").fadeOut(100);
 		$("#login-form").fadeOut(100);
		$('#register-form-link').removeClass('active');
		$('#login-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});
	$('#register-form-link').click(function(e) {
		$("#register-form").delay(100).fadeIn(100);
 		$("#login-form").fadeOut(100);
 		$("#forgot-form").fadeOut(100);
		$('#login-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});
        $("#forgot-submit").click(function (event) {
{#            $(this).val('Sending ...');#}
            $(this).prop('disabled', true);
            $.ajax({
                type: "POST",
                url: "/password_reset/",
                data: {
                    'email': $('#id_email').val() // from form
                },

                success: function (event) {
                    $("#success-message-forgot").show(1000);
                    $("#forgot-submit").removeProp("disabled");
                }
            });
            return false; //<---- move it here
        });


});
</script>

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="#" class="active" id="login-form-link">Login</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" id="register-form-link">Register</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form id="login-form" method="post" role="form" style="display: block;">
                                <div class="form-group">
                                    <input type="text" name="email" id="email" tabindex="1" class="form-control"
                                           placeholder="Username" value="">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" id="password" tabindex="2"
                                           class="form-control" placeholder="Password">
                                </div>
                                <div class="form-group text-center">
                                    <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                                    <label for="remember"> Remember Me</label>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="submit" id="login-submit" tabindex="4"
                                                   class="form-control btn btn-login" value="Sign In">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="text-center">
                                                <a href="{% url 'password_reset' %}" tabindex="5"
                                                   class="forgot-password">Forgot Password?</a>
                                                <a href="{% url 'index' %}" tabindex="5">Back to Home</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <form id="register-form" method="post" role="form" style="display: none;">
                                <div class="form-group">
                                    <input type="text" name="first_name" id="first_name" tabindex="1"
                                           class="form-control" placeholder="First name" value="">
                                </div>
                                <div class="form-group">
                                    <input type="text" name="last_name" id="last_name" tabindex="1" class="form-control"
                                           placeholder="Last name" value="">
                                </div>
                                <div class="form-group">
                                    <input type="email" name="email" id="email" tabindex="1" class="form-control"
                                           placeholder="Email Address" value="">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password1" id="password1" tabindex="2"
                                           class="form-control" placeholder="Password">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password2" id="password2" tabindex="2"
                                           class="form-control" placeholder="Confirm Password">
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="submit" id="register-submit" tabindex="4"
                                                   class="form-control btn btn-register" value="Sign Up">
                                        </div>
                                    </div>
                                </div>
                            </form>

                            {# FORGOT FORM #}

                            <form id="forgot-form" method="post" role="form" style="display: block;">
                                <div id="success-message-forgot" class="alert alert-info fade in" style="display: none;">
                                    <strong>Note!</strong>    Email was sent. Check your mail.
                                </div>
                                <div class="form-group">
                                    <input type="email" name="email" required id="id_email" tabindex="1" class="form-control"
                                           placeholder="Email address" value="">
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="submit" id="forgot-submit" tabindex="4"
                                                   class="form-control btn btn-login" value="Send">
                                        </div>
                                    </div>
                                </div>
                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block main_block %}
    <form method="post">
        {% csrf_token %}
        <div class="row">

            <div class="col-md-6 col-md-offset-3">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

                <div class="form-group">
                    <label for="id_email">Email address</label>
                    <input type="email" name="email" class="form-control" id="id_email" aria-describedby="emailHelp"
                           placeholder="Enter email" value={{ request.user.email }}>
                    <small id="emailHelp" class="form-text text-muted">This's a your account name.
                    </small>
                </div>
                <div class="form-group">
                    <label for="id_first_name">First name</label>
                    <input type="text" class="form-control" id="id_first_name" name="first_name"
                           placeholder="First name" value={{ request.user.first_name }}>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last name</label>
                    <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Last name"
                           value={{ request.user.last_name }}>
                </div>

                <button type="submit" class="btn btn-success btn-lg btn-block">Update Profile</button>

            </div>
        </div>
    </form>


    {#    <form method="post">#}
    {#        {% csrf_token %}#}
    {#        {{ form.as_p }}#}
    {#        <button type="submit">Update Profile</button>#}
    {#    </form>#}
{% endblock %}